version: '3.9'

services:
  web:
    image: labstand-site:latest
    environment:
      - VIRTUAL_HOST=labstand.myfamcloud.ml
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=labstand.myfamcloud.ml
      - LETSENCRYPT_EMAIL=nikitamishagin@gmail.com
    networks:
      - homecloud_proxy-tier
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: rollback
        monitor: 10s
        order: stop-first
      restart_policy:
        condition: on-failure
