version: '3.9'

services:
  web:
    image: nikitamishagin/portfolio-web:latest
    env_file:
      - vhost.env
    networks:
      - proxy
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: rollback
        monitor: 10s
        order: stop-first
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true
    name: reverse-proxy_proxy
