pipeline {
  agent any
  stages {
    stage('Build-docker-image') {
      steps{
        sh 'echo ${GIT_COMMIT}'
        sh 'docker build -t portfolio-web:${GIT_COMMIT} .'
        sh 'docker tag portfolio-web:${GIT_COMMIT} portfolio-web:latest'
      }
    }
  }
}
